# Algoritmos de optimización - Trabajo Práctico

**Nombre y Apellidos**: Alejandro Ciriano

**Repositorio**: https://github.com/aciriano/optimization/blob/main/trabajo.ipynb

**Cuaderno**: https://drive.google.com/file/d/1Gy5Y747oyCGkRB_QYZduAhRk1fxipSgn/view?usp=sharing

**Problema**: Sesiones de doblaje

**Descripción del problema**: Se precisa coordinar el doblaje de una película. Los actores del doblaje deben coincidir en las tomas en las que sus personajes aparecen juntos en las diferentes tomas. Los actores de doblaje cobran todos la misma cantidad por cada día que deben desplazarse hasta el estudio de grabación independientemente del número de tomas que se graben. No es posible grabar más de 6 tomas por día. El objetivo es planificar las sesiones por día de manera que el gasto por los servicios de los actores de doblaje sea el menor posible.

Los datos son:

- Número de actores: 10
- Número de tomas: 30
- Actores/Tomas: https://bit.ly/36D8IuK (1 participa, 0 no)

| Toma | Actor 1 | Actor 2 | Actor 3 | Actor 4 | Actor 5 | Actor 6 | Actor 7 | Actor 8 | Actor 9 | Actor 10 | Total |
|------|---------|---------|---------|---------|---------|---------|---------|---------|---------|----------|-------|
| 1  | 1 | 1 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 5 |
| 2  | 0 | 0 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 3 |
| 3  | 0 | 1 | 0 | 0 | 1 | 0 | 1 | 0 | 0 | 0 | 3 |
| 4  | 1 | 1 | 0 | 0 | 0 | 0 | 1 | 1 | 0 | 0 | 4 |
| 5  | 0 | 1 | 0 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 3 |
| 6  | 1 | 1 | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 4 |
| 7  | 1 | 1 | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 4 |
| 8  | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 3 |
| 9  | 1 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 3 |
| 10 | 1 | 1 | 0 | 0 | 0 | 1 | 0 | 0 | 1 | 0 | 4 |
| 11 | 1 | 1 | 1 | 0 | 1 | 0 | 0 | 1 | 0 | 0 | 5 |
| 12 | 1 | 1 | 1 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | 5 |
| 13 | 1 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 3 |
| 14 | 1 | 0 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 3 |
| 15 | 1 | 1 | 0 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 3 |
| 16 | 0 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 1 | 2 |
| 17 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 2 |
| 18 | 0 | 0 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 2 |
| 19 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 2 |
| 20 | 1 | 0 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 4 |
| 21 | 0 | 0 | 0 | 0 | 0 | 1 | 0 | 1 | 0 | 0 | 2 |
| 22 | 1 | 1 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 4 |
| 23 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 2 |
| 24 | 0 | 0 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 2 |
| 25 | 1 | 1 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 1 | 4 |
| 26 | 1 | 0 | 1 | 0 | 1 | 0 | 0 | 0 | 1 | 0 | 4 |
| 27 | 0 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 0 | 2 |
| 28 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 2 |
| 29 | 1 | 0 | 0 | 0 | 1 | 1 | 0 | 0 | 0 | 0 | 3 |
| 30 | 1 | 0 | 0 | 1 | 0 | 0 | 0 | 0 | 0 | 0 | 2 |
| **TOTAL** | **22** | **14** | **13** | **15** | **11** | **8** | **3** | **4** | **2** | **2** |   |





                                        

# 1. Breve análisis y formulación

Las siguientes observaciones representan un análisis preliminar del problema. Ayudaron a resolver los distintos apartados del trabajo.

1. Una producción audiovisual debe grabar un conjunto de $k$ escenas, en el orden en el que se quiera, manteniendo un límite diario $L$.

    $$
    S = \\{ s_1, s_2, \dots ,s_k\\}
    $$

2. El objetivo del problema es minimizar el coste de grabación total $C$, el cual se define como la suma del número de días que cada uno de los actores $a_n$ tiene que viajar al set de grabación.
    
    $$
    C = \sum_{n=1}^{N}a_{n}
    $$

    Por ejemplo, si $N=3$ (hay 3 actores) y cada actor debe acudir 2 días ($a_n=2$), el coste total es 6. Sin embargo, si cada uno sólo tiene que ir un día, el coste es 3. El objetivo es organizarlos de tal forma que se minimice $C$.

3. Las escenas con más actores son las más caras, ya que todos deben acudir ese día. Los actores con más escenas son, potencialmente, los más caros (depende de la organización).

4. Las mejores soluciones pueden no utilizar el mínimo número de días posible. Por ejemplo, si cada día se puede grabar 5 veces, y tienes 3 actores que aparecen sólos en 3 escenas cada uno, es mejor no ocupar todas las grabaciones de cada día: `AAAXX|BBBXX|CCCXX` (coste 3) es más barato que `AAABB|BCCCX` (coste 4).

5. Hay un límite superior al número de días requeridos para realizar la grabación, que es, naturalmente, el número de escenas a grabar (una por día). También hay una cota inferior, que es el número de escenas total entre el número de posibles grabaciones diarias (o más 1, dependiendo de si el módulo es cero o no).

    $$
    \frac{k}{L} \le d \le k
    $$

    En el problema propuesto, el número de días queda delimitado en el intervalo $5 \le d \le 30$.

6. El coste también está acotado. En el mejor caso, todos los actores tienes que acudir solo una vez ($a_n=1, \; ∀ n$), mientras que, en el peor caso, deben acudir todos los días, con una escena por día ($a_n=k, \; ∀ n$).

    $$
    N \le C \le N · k
    $$

    Dado una distribución concreta de escenas y actores, el valor mínimo puede ajustarse aún más teniendo en cuenta el número mínimo de días que cada actor tiene que acudir a grabar, teniendo en cuenta el máximo diario.

    En el problema propuesto, la suma de los costes mínimos de cada uno de los actores es $C_{min} = 4 + 3 + 3 + 3 + 2 + 2 + 1 + 1 + 1 + 1 = 21$.

7. Es posible representar la solución de distintas formas. Por ejemplo, una lista en la que el índice representa la escena y el valor el día asignado, o un diccionario en el que la clave es la escena y el valor el día de grabación. No son las únicas, y la forma de construir la solución influirá en qué estructura utilizar.

8. Una simplificación válida del problema consiste en fijar el número de días _a priori_, de tal forma que los algoritmos no tengan que explorar todas las distintas combinaciones de huecos entre días. Eso no significa que luego no se experimente con distintos valores.

9. Si el número de días $d$ es fijo, las soluciones pueden representarse directamente como $d$ conjuntos de números naturales, que representan las escenas a grabar ese día. Esto, a su vez, puede representarse en forma matricial.

# 2. Modelo

Para facilitar el análisis y los modelos, se ha optado por asumir que el número de días $d$ utilizados para grabar es fijo. Tal y como se ha indicado, la condición que se debe cumplir es $\frac{k}{L}\le d \le k$.


- **¿Como represento el espacio de soluciones?**
    
    El sistema escogido se basa en una matriz booleana $M$, de $d$ filas y $k$ columnas, en la que cada valor $(i,j)$ indica si la escena $j$ se graba el día $i$.

    Ejemplo para 5 escenas, 3 días y un máximo de 2 escenas por día:
    ```python
    M = [
        [1, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 1],
    ]
    ```

- **¿Cual es la función objetivo?**

    La función a minimizar es el número de viajes realizados por los actores. Para saber cuántos actores deben acudir cada día, hay que utilizar la distribución $V$ (matriz del enunciado) de escenas y actores.

    Cuando multiplicamos la matriz solución $M$, cuyas dimensiones son ($d$, $k$), con la matriz $V$, cuyas dimensiones son ($k$, $N$), obtenemos una matriz ($d$, $N$) que representa el número de grabaciones que cada actor tiene que acometer cada día.

    Dado que nos interesa saber si un actor tiene que viajar para grabar un día, sin importar el número de tomas, nos basta con contar el número de elementos no nulos de la matriz resultante.

    ```python
    import numpy as np

    # Solución propuesta: días en las filas, escenas en las columnas.
    M = [
        [1, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 1],
    ]

    # Enunciado: escenas en las filas, actores en las columnas.
    V = [
        [1, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 1],
        [0, 0, 1, 0],
        [1, 1, 0, 0],
    ]
    
    # Resultado: días en las filas, actores en las columnas.
    np.array(M) @ np.array(V)
    # [1, 0, 2, 1]
    # [0, 1, 0, 0]
    # [1, 1, 1, 0]

    np.count_nonzero(_)
    # 7
    ```

- **¿Como implemento las restricciones?**

    Dada la matriz solución $M$, hay 2 condiciones que esta debe cumplir:

    1. La suma de sus columnas tiene que ser un array con todo 1s. Esto significa que cada escena se graba exactamente en un día.

    2. La suma de sus filas no debe superar el valor $L$. Esto significa que cada día no se graban más escenas de las posibles.

    ```python
    import numpy as np

    M = np.array([
        [1, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 1],
    ])

    M.sum(axis=0)
    # array([1, 1, 1, 1, 1])

    M.sum(axis=1)
    # array([2, 1, 2])

    # Un ejemplo erróneo en el que no se asigna día a una escena.
    M = np.array([
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 1],
    ])
    M.sum(axis=0)
    # array([0, 1, 1, 1, 1])

    # Un ejemplo erróneo en el que se supera el límite.
    M = np.array([
        [1, 0, 1, 1, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
    ])
    M.sum(axis=1)
    # array([3, 1, 1])
    ```

## 2.1 Clases y funciones

In [1]:
import dataclasses
from time import perf_counter
import random

import pandas as pd
import numpy as np
import numpy.typing as npt


class VoiceCast:
    """
    Class which represents and stores data about the cast and the
    relation between actors and scenes.

    Problema definition is loaded in an instance of this class.
    """
    def __init__(self, distribution: npt.NDArray[np.uint8]) -> None:
        self.distribution = distribution
        self.scenes, self.actors = self.distribution.shape

    def total_actors_in_scene(self, scene: int) -> int:
        return np.sum(self.distribution[scene, :])

    def get_scenes_for_actor(self, actor: int) -> set[int]:
        scenes = np.where(self.distribution[:, actor] == 1)[0]
        return set(map(int, scenes))

    def get_actors_for_scene(self, scene: int) -> set[int]:
        actors = np.where(self.distribution[scene] == 1)[0]
        return set(map(int, actors))

    def actors_correlation(self):
        """Return a dictionary with the number of shared scenes between actors."""
        out = {}
        for actor in range(self.actors):
            out[actor+1] = {i+1:0 for i in range(self.actors)}
            for scene in self.get_scenes_for_actor(actor):
                for j in self.get_actors_for_scene(scene):
                    out[actor+1][j+1] += 1

        return out


@dataclasses.dataclass
class VoiceCastProblem:
    """
    A tuple used to model the original problem, in which there is a set
    of scenes and actors and a limit of scenes to record per day.
    """
    cast: VoiceCast
    limit: int


# Alias for typing annotation.
Solution = npt.NDArray[np.uint8]


def random_solution(problem: VoiceCastProblem, days: int) -> Solution:
    """Builds a random solution for a given problem and a given number of days."""
    solution = np.zeros((days, problem.cast.scenes), dtype=np.uint8)
    recount = {i: 0 for i in range(days)}
    for scene in range(problem.cast.scenes):
        options = [i for i in recount if recount[i] < problem.limit]
        chosen = random.choice(options)
        recount[chosen] += 1
        solution[chosen][scene] = 1

    return solution


def check_solution(problem: VoiceCastProblem, solution: Solution) -> bool:
    """Checks if a candidate solution matches all constraints."""
    return (
        solution.shape[1] == problem.cast.scenes and
        np.all(solution.sum(axis=0) == 1) and
        solution.sum(axis=1).max() <= problem.limit
    )


def evaluate_solution(problem: VoiceCastProblem, solution: Solution) -> int:
    """Return the cost of a given solution. Raises an error if it is not valid."""
    if not check_solution(problem, solution):
        raise ValueError(f"Invalid solution: {solution}.")

    return np.count_nonzero(solution @ problem.cast.distribution)


def describe_solution(solution: Solution, problem: VoiceCastProblem) -> None:
    """Prints information about a given solution in matrix format."""
    for d, day in enumerate(solution):
        scenes = {int(j+1) for j in np.where(day==1)[0]}
        print(f"El día {d+1} se graban {len(scenes)} escenas: {scenes}.")

        actors = set().union(*(problem.cast.get_actors_for_scene(i-1) for i in scenes))
        print(f"Actores requeridos: {set(i+1 for i in actors)}.\n")

## 2.2 Validación

En esta celda se verifica que el código anterior es correcto y funciona de acuerdo a lo esperado.

In [2]:
def test_voice_cast() -> None:
    scenes = [
        [1, 0, 0, 0],
        [1, 1, 0, 0],
        [0, 0, 1, 1]
    ]
    scenes = np.array(scenes, dtype=np.uint8)
    voice_cast = VoiceCast(distribution=scenes)
    assert voice_cast.scenes == 3
    assert voice_cast.actors == 4
    assert voice_cast.total_actors_in_scene(0) == 1
    assert voice_cast.total_actors_in_scene(1) == 2
    assert voice_cast.total_actors_in_scene(2) == 2
    assert voice_cast.get_actors_for_scene(0) == {0}
    assert voice_cast.get_actors_for_scene(1) == {0, 1}
    assert voice_cast.get_actors_for_scene(2) == {2, 3}
    assert voice_cast.get_scenes_for_actor(0) == {0, 1}
    assert voice_cast.get_scenes_for_actor(1) == {1}
    assert voice_cast.get_scenes_for_actor(2) == {2}
    assert voice_cast.get_scenes_for_actor(3) == {2}


def test_voice_cast_problem():
    # Scenes distribution.
    scenes = [
        [1, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 1],
        [0, 0, 1, 0],
        [1, 1, 0, 0],
    ]
    scenes = np.array(scenes, dtype=np.uint8)
    voice_cast = VoiceCast(distribution=scenes)
    problem = VoiceCastProblem(cast=voice_cast, limit=2)

    # Create a solution and validate it.
    solution = [
        [1, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 1],
    ]
    solution = np.array(solution, dtype=np.uint8)

    assert evaluate_solution(problem=problem, solution=solution) == 7


def test_random_solution(iters: int = 10):
    # Scenes distribution.
    scenes = [
        [1, 0, 1, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 1],
        [0, 0, 1, 0],
        [1, 1, 0, 0],
    ]
    scenes = np.array(scenes, dtype=np.uint8)
    voice_cast = VoiceCast(distribution=scenes)
    problem = VoiceCastProblem(cast=voice_cast, limit=2)

    for _ in range(iters):
        sol = random_solution(problem=problem, days=3)
        cost = evaluate_solution(problem=problem, solution=sol)
        print(f"Random solution:")
        print(sol)
        print(f"Cost: {cost}.")


test_voice_cast()
test_voice_cast_problem()
test_random_solution(iters=1)

Random solution:
[[1 0 0 0 0]
 [0 0 0 1 1]
 [0 1 1 0 0]]
Cost: 8.


## 2.3 Instancia del problema

Aquí se crea el problema a resolver en el trabajo. Los datos son importados manualmente desde el enlace ya que, en este caso, es la forma más sencilla y rápida.

In [3]:
# Number of scenes that can be recorded per day.
MAX_PER_DAY = 6

# Scenes and actors appearances.
SCENES = [
    [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 1, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 1, 0, 0],
    [0, 1, 0, 1, 0, 0, 0, 1, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 0, 1, 0],
    [1, 1, 1, 0, 1, 0, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
    [1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
    [1, 0, 1, 0, 1, 0, 0, 0, 1, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 1, 0, 0, 0, 0],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0]
]


# Data which defines the problem instance.
voice_cast = VoiceCast(distribution=np.array(SCENES, dtype=np.uint8))
for i in range(voice_cast.actors):
    i_total = voice_cast.get_scenes_for_actor(i)
    print(f"El actor {i+1} aparece en {len(i_total)} escenas.")

# Problem instance to be solved.
vc_problem = VoiceCastProblem(cast=voice_cast, limit=MAX_PER_DAY)

# Correlation between actors.
print(f"\nLa siguiente matriz representa la coincidencia de actores en las escenas:")
pd.DataFrame(voice_cast.actors_correlation())

El actor 1 aparece en 22 escenas.
El actor 2 aparece en 14 escenas.
El actor 3 aparece en 13 escenas.
El actor 4 aparece en 15 escenas.
El actor 5 aparece en 11 escenas.
El actor 6 aparece en 8 escenas.
El actor 7 aparece en 3 escenas.
El actor 8 aparece en 4 escenas.
El actor 9 aparece en 2 escenas.
El actor 10 aparece en 2 escenas.

La siguiente matriz representa la coincidencia de actores en las escenas:


,1,2,3,4,5,6,7,8,9,10
1,22,12,10,11,8,5,2,2,2,1
2,12,14,4,8,5,3,3,3,1,1
3,10,4,13,5,5,4,0,1,1,0
4,11,8,5,15,7,1,0,1,0,2
5,8,5,5,7,11,1,1,1,1,0
6,5,3,4,1,1,8,0,1,1,0
7,2,3,0,0,1,0,3,1,0,0
8,2,3,1,1,1,1,1,4,0,0
9,2,1,1,0,1,1,0,0,2,0
10,1,1,0,2,0,0,0,0,0,2


# 3. Análisis

**¿Que complejidad tiene el problema? Orden de complejidad y contabilizar el espacio de soluciones.**

Dada la matriz solución $M$, de dimensiones ($d$, $k$), y sabiendo que en cada columna sólo puede haber un 1, podemos establecer el límite superior del número de soluciones en $d^k$. Esto es así porque en la primera columna hay $d$ posibilidades, en la segunda igual, y, así, hasta la última escena ($k$). Este es un límite superior calculado sin imponer las restricciones del número de días.

Es posible imponer las restricciones y mejorar la estimación del número máximo de soluciones asumiendo que **todos los días se graba el mismo número de escenas**. Si todos los días se graban $L$ escenas, entonces existen $\binom{k}{L}$ combinaciones para el primer grupo, $\binom{k-L}{L}$ para el segundo, $\binom{k-2L}{L}$ para el tercero, etc.

Si hay $d$ grupos de $L$ elementos, y se asume que $dL=k$ (el número de escenas es igual al número de días por el límite de grabación diario), entonces el total de combinaciones es:
$$
\prod_{i=0}^{d-1} \binom{k - iL}{L} = \binom{k}{L} \cdot \binom{k-L}{L} \dots \binom{k-(d-2)L}{L} \binom{k-(d-1)L}{L}
$$


Si se desarrolla el productorio, se obtiene la siguiente expresión:
$$
\prod_{i=0}^{d-1} \binom{k - iL}{L} = \frac{k!}{L!(k-L)!} \frac{(k-L)!}{L!(k-2L)!} \dots \frac{(k-(d-2)L)!}{L!(k-(d-1)L)!} = \frac{k!}{(L!)^d}
$$

En el caso del problema propuesto, el número de combinaciones es:
$$
\prod_{i=0}^{5-1} \binom{30 - 6i}{6} = \frac{30!}{(6!)^5} ≈ 1.37*10^{18}
$$

Aunque no se han abordado todos los casos posibles y se han hecho supuestos, la formulación anterior indica que el orden de complejidad del problema es **exponencial** (el productorio depende de $k!$).

# 4. Diseño

**¿Que técnica utilizo? ¿Por qué?**

Se va a resolver con <u>algoritmos genéticos</u>. Otras opciones válidas podrían ser búsquedas locales o técnicas de *back-tracking*, pero se ha considerado que el espacio de soluciones es demasiado grande para ello. Además, es posible definir fácilmente todas las funciones que componen los procesos genéticos y aplicarlas sobre las matrices que modelan la solución del problema propuesto.

1. **Descendencia**. Dado que dos soluciones (padre y madre) son matrices con mismas dimensiones y valores {0,1}, es posible crear una nueva con la mitad de escenas de cada uno de los padres. Otra opción sería sumarlas, pero adaptar el resultado final (hacerlo factible) es un poco más complejo.

2. **Mutación**: Una mutación de una solución valida puede implementarse como la permutación de los días de grabación de 2 o más escenas, las cuales no son grabadas el mismo día (hay más opciones). Tal y como se ha modelado la solución, basta con intercambiar $n$ columnas entre sí.

3. **Factibilidad**: Es improbable que los descendientes sean soluciones válidas. Para adaptarlos, se hace lo siguiente: se detectan los días con más grabaciones de las posibles, y se cuentan los huecos que quedan en el resto de días. Dado que los huecos son, necesariamente, mayores o iguales al exceso de escenas en los días sobreocupados, basta con hacer un re-reparto aleatorio de escenas de los días que no cumplen la limitación hacia los días con espacio para nuevas grabaciones.

```python
father = [
    [1 0 1 0],
    [0 1 0 0],      
    [0 0 0 1]       
]

mother = [
    [0 0 0 0],
    [1 0 1 0],
    [0 1 0 1]
]

son = [
    [1 0 0 0],
    [0 1 1 0],
    [0 0 0 1]
]

assert is_valid(son)

mutate(son)
[
    [0 0 0 1],
    [0 1 1 0],
    [1 0 0 0]
]
```

## 4.1 Algoritmos Genéticos

Las siguientes celdas incluyen la implementación realizada de algoritmos genéticos aplicados al problema.

In [4]:
class GeneticProcess:
    """
    Implements a genetic algorithm–based process to generate solutions for
    the voice cast scheduling problem, which aims to determine the optimal
    allocation of actors across different recording days while maximizing
    efficiency and satisfying the established constraints.
    """
    def __init__(self, problem: VoiceCastProblem, days: int) -> None:
        """
        Initialization requires a problem instance and a predefined number of days.
        """
        self.problem = problem
        self.days = days

    def new_population(self, size: int) -> list[Solution]:
        """Creates a new population of solutions with a given size."""
        return [random_solution(self.problem, self.days) for _ in range(size)]

    def find_best(self, population: list[Solution]) -> tuple[Solution, int]:
        """Given a list of solutions, return the solution with the lowest cost."""
        best, best_cost = None, float("inf")
        for solution in population:
            cost = evaluate_solution(problem=self.problem, solution=solution)
            if cost < best_cost:
                best, best_cost = solution, cost
        return best, best_cost

    def mutate(self, solution: Solution) -> Solution:
        """Applies a 2-opt to transform the input solution in a new one."""
        a, b = random.sample(range(solution.shape[1]), k=2)
        solution[:, [a, b]] = solution[:, [b, a]]
        return solution

    def new_son(self, father: Solution, mother: Solution) -> Solution:
        """
        Creates a new solution based on the left side columns of the father,
        and the right columns of the mother.

        Before returning the new solution, the son is transformed by the
        _make_feasible function.
        """
        middle = father.shape[1] // 2

        # Split the matrix in two different parts.
        left_part = father[:, :middle]
        right_part = mother[:, middle:]

        # Concatenate to create the new son.
        son = np.concatenate((left_part, right_part), axis=1)

        return self._make_feasible(son) if not check_solution(self.problem, son) else son

    def create_offspring(self, population: list[Solution], p_mut: float) -> list[Solution]:
        """
        Given a list of solutions, this function returns a list of len(population)^2/2
        new solutions which are built using the current ones.

        As the son is created with the left part of the father, the roles of the
        parents are chosen randomly.
        """
        offspring = []
        for i in range(len(population)-1):
            for j in range(i+1, len(population)):
                if random.random() <= 0.5:
                    son = self.new_son(father=population[i], mother=population[j])
                else:
                    son = self.new_son(father=population[j], mother=population[i])

                if random.random() <= p_mut:
                    son = self.mutate(son)

                offspring.append(son)
        return offspring

    def _make_feasible(self, candidate: npt.NDArray[np.uint8]) -> Solution:
        """
        Given a son, which is built using the left side of the father and
        the right side of the mother, this functions changes those scenes
        which have been scheduled in a day (sum of rows) with more scenes
        than the limit.

        It detects days with less scenes than the limit, and it moves some
        scenes in the invalid days to another one with free slots (move 1s
        from one row to another row, while keeping the total scenes in the
        new day below the limit).
        """
        # First, sum the rows in order to detect errors and free slots.
        scenes_per_day = candidate.sum(axis=1)
        free, occupied = [], []
        for d, recount in enumerate(scenes_per_day):
            diff = int(recount) - self.problem.limit
            if diff > 0:
                for _ in range(diff):
                    occupied.append(d)
            elif diff < 0:
                for _ in range(-diff):
                    free.append(d)

        for occ in occupied:
            # occ represents the day which has to be changed. It could be
            # in the occupied list more than once.
            new_day = free.pop(random.randint(0, len(free)-1))

            # we are moving an scene from day occ to day new_day. Now, we have
            # to select one scene of the occupied day.
            scenes_in_day = np.where(candidate[occ, :] == 1)[0]
            chosen = random.choice(scenes_in_day)

            # Move the scene
            candidate[occ, chosen] = 0
            candidate[new_day, chosen] = 1

        assert check_solution(self.problem, candidate), "Candidate has not been corrected."

        return candidate

    def filter_population(
            self,
            population: list[Solution],
            offspring: list[Solution],
            size: int,
            elitism: float
        ) -> list[Solution]:
        """
        Filters the current population using elitism and offspring integration.

        This method preserves a percentage of the best individuals from the
        current population (elitism) and fills the remaining slots with the
        best candidates selected from the rest of the population combined
        with the offspring.
        """
        n_elitism = int(elitism * len(population))
        sorted_population = sorted(population, key=lambda x: evaluate_solution(self.problem, x))
        elite, others = sorted_population[:n_elitism], sorted_population[n_elitism:]
        to_choose = size - len(elite)
        others += offspring
        others = sorted(others, key=lambda x: evaluate_solution(self.problem, x))
        return elite + others[:to_choose]

    def run(self, pop_size: int, p_mut: float, generations: int, elitism: float) -> tuple[Solution, int]:
        """Run the whole process."""
        best, cost = None, float("inf")

        # Initialize population.
        population = self.new_population(size=pop_size)

        # Run the evolution process `generations` times.
        for generation_number in range(1, generations+1):
            offspring = self.create_offspring(population=population, p_mut=p_mut)
            population = self.filter_population(population, offspring, pop_size, elitism)
            best, cost = self.find_best(population=population)

            if (generation_number % 10 == 0) or (generation_number // 10 == 0):
                print(f"\tGeneration {generation_number:03d}. Best result: {cost}.")

        return best, cost

In [5]:
# Set the seed in order to replicate the experiments.
random.seed(9482)

In [6]:
start = perf_counter()
print("Running process with 5 days:")
process = GeneticProcess(problem=vc_problem, days=5)
best_5, cost_5 = process.run(pop_size=100, p_mut=0.1, generations=100, elitism=0.03)
print(f"Ending process with 5 days. Time = {(perf_counter() - start):.4f}.\n")

describe_solution(best_5, vc_problem)

Running process with 5 days:
	Generation 001. Best result: 33.
	Generation 002. Best result: 32.
	Generation 003. Best result: 31.
	Generation 004. Best result: 30.
	Generation 005. Best result: 29.
	Generation 006. Best result: 28.
	Generation 007. Best result: 27.
	Generation 008. Best result: 27.
	Generation 009. Best result: 27.
	Generation 010. Best result: 27.
	Generation 020. Best result: 27.
	Generation 030. Best result: 27.
	Generation 040. Best result: 27.
	Generation 050. Best result: 27.
	Generation 060. Best result: 27.
	Generation 070. Best result: 27.
	Generation 080. Best result: 27.
	Generation 090. Best result: 27.
	Generation 100. Best result: 27.
Ending process with 5 days. Time = 29.5517.

El día 1 se graban 6 escenas: {14, 17, 18, 19, 23, 24}.
Actores requeridos: {1, 3, 6}.

El día 2 se graban 6 escenas: {1, 2, 5, 11, 20, 22}.
Actores requeridos: {1, 2, 3, 4, 5, 8}.

El día 3 se graban 6 escenas: {3, 4, 8, 15, 21, 29}.
Actores requeridos: {1, 2, 5, 6, 7, 8}.

El d

In [7]:
start = perf_counter()
print("Running process with 6 days:")
process = GeneticProcess(problem=vc_problem, days=6)
best_6, cost_6 = process.run(pop_size=100, p_mut=0.05, generations=100, elitism=0.03)
print(f"Ending process with 6 days. Time = {(perf_counter() - start):.4f}.\n")

describe_solution(best_6, vc_problem)

Running process with 6 days:
	Generation 001. Best result: 35.
	Generation 002. Best result: 35.
	Generation 003. Best result: 34.
	Generation 004. Best result: 34.
	Generation 005. Best result: 33.
	Generation 006. Best result: 33.
	Generation 007. Best result: 32.
	Generation 008. Best result: 32.
	Generation 009. Best result: 32.
	Generation 010. Best result: 31.
	Generation 020. Best result: 31.
	Generation 030. Best result: 31.
	Generation 040. Best result: 31.
	Generation 050. Best result: 31.
	Generation 060. Best result: 31.
	Generation 070. Best result: 31.
	Generation 080. Best result: 31.
	Generation 090. Best result: 31.
	Generation 100. Best result: 31.
Ending process with 6 days. Time = 24.0085.

El día 1 se graban 5 escenas: {14, 18, 19, 23, 24}.
Actores requeridos: {1, 3, 6}.

El día 2 se graban 6 escenas: {4, 5, 16, 25, 28, 30}.
Actores requeridos: {1, 2, 4, 7, 8, 10}.

El día 3 se graban 2 escenas: {8, 10}.
Actores requeridos: {1, 2, 6, 9}.

El día 4 se graban 6 escen

## 4.2 Búsqueda local

Tras realizar la simulación con procesos genéticos, se observa que el tiempo requerido es más elevado del esperado. Esto se debe, principalmente, a la generación de la descendencia. Para mejorar los resultados, se propone utilizar técnicas de búsqueda local tanto para generar la población inicial como para explotar las soluciones obtenidas al final del proceso.

In [8]:
def local_search(solution: Solution, problem: VoiceCastProblem) -> Solution:
    """
    Given a (good) solution, this function applies 2-opt transformation
    recursively until no better solution is found.
    """
    best, best_cost = solution, evaluate_solution(problem, solution)
    for i in range(solution.shape[1]):
        for j in range(i+1, solution.shape[1]):
            candidate = solution.copy()
            candidate[:, [i, j]] = candidate[:, [j, i]]
            candidate_cost = evaluate_solution(problem, candidate)
            if candidate_cost < best_cost:
                return local_search(candidate, problem)
    return best, best_cost


class GeneticProcessWithLocalSearch(GeneticProcess):
    """
    This class updates the original genetic algorithm simply by changing the
    way in which the initial population is built.
    """
    def new_population(self, size: int) -> list[Solution]:
        return [
            local_search(
                random_solution(self.problem, self.days),
                self.problem
            )[0]
            for _ in range(size)
        ]

improved_5, improved_5_cost = local_search(best_5, vc_problem)
print(f"Best result in 5 days after local search: {improved_5_cost}.")

improved_6, improved_6_cost = local_search(best_6, vc_problem)
print(f"Best result in 6 days after local search: {improved_6_cost}.")

Best result in 5 days after local search: 27.
Best result in 6 days after local search: 31.


In [9]:
start = perf_counter()
print("Running process with 5 days and local search:")
process = GeneticProcessWithLocalSearch(problem=vc_problem, days=5)
best_5_ls, cost_5_ls = process.run(pop_size=100, p_mut=0.1, generations=100, elitism=0.1)
print(f"Ending process with 5 days and local search. Time = {(perf_counter() - start):.4f}.\n")

best_5_ls, cost_5_ls = local_search(best_5_ls, vc_problem)
print(f"After applying local search to final solution: {cost_5_ls}.\n")

describe_solution(best_5_ls, vc_problem)

Running process with 5 days and local search:
	Generation 001. Best result: 27.
	Generation 002. Best result: 27.
	Generation 003. Best result: 27.
	Generation 004. Best result: 27.
	Generation 005. Best result: 27.
	Generation 006. Best result: 27.
	Generation 007. Best result: 27.
	Generation 008. Best result: 27.
	Generation 009. Best result: 27.
	Generation 010. Best result: 27.
	Generation 020. Best result: 27.
	Generation 030. Best result: 27.
	Generation 040. Best result: 27.
	Generation 050. Best result: 27.
	Generation 060. Best result: 27.
	Generation 070. Best result: 27.
	Generation 080. Best result: 27.
	Generation 090. Best result: 27.
	Generation 100. Best result: 27.
Ending process with 5 days and local search. Time = 26.2551.

After applying local search to final solution: 27.

El día 1 se graban 6 escenas: {14, 17, 18, 19, 23, 24}.
Actores requeridos: {1, 3, 6}.

El día 2 se graban 6 escenas: {2, 20, 26, 27, 28, 30}.
Actores requeridos: {1, 3, 4, 5, 9}.

El día 3 se g

In [10]:
start = perf_counter()
print("Running process with 6 days and local search:")
process = GeneticProcessWithLocalSearch(problem=vc_problem, days=6)
best_6_ls, cost_6_ls = process.run(pop_size=100, p_mut=0.1, generations=100, elitism=0.1)
print(f"Ending process with 6 days and local search. Time = {(perf_counter() - start):.4f}.\n")

best_6_ls, cost_6_ls = local_search(best_6_ls, vc_problem)
print(f"After applying local search to final solution: {cost_6_ls}.\n")

describe_solution(best_6_ls, vc_problem)

Running process with 6 days and local search:
	Generation 001. Best result: 30.
	Generation 002. Best result: 30.
	Generation 003. Best result: 30.
	Generation 004. Best result: 30.
	Generation 005. Best result: 30.
	Generation 006. Best result: 30.
	Generation 007. Best result: 30.
	Generation 008. Best result: 30.
	Generation 009. Best result: 30.
	Generation 010. Best result: 30.
	Generation 020. Best result: 30.
	Generation 030. Best result: 30.
	Generation 040. Best result: 30.
	Generation 050. Best result: 30.
	Generation 060. Best result: 30.
	Generation 070. Best result: 30.
	Generation 080. Best result: 30.
	Generation 090. Best result: 30.
	Generation 100. Best result: 30.
Ending process with 6 days and local search. Time = 29.0148.

After applying local search to final solution: 30.

El día 1 se graban 5 escenas: {9, 16, 25, 28, 30}.
Actores requeridos: {1, 2, 10, 4}.

El día 2 se graban 2 escenas: {24, 18}.
Actores requeridos: {3, 6}.

El día 3 se graban 5 escenas: {3, 4, 5

# 5. Conclusiones

1. En este trabajo se ha formulado y modelado un problema de planificación que consiste en organizar a 10 actores de doblaje para completar la grabación de 30 escenas, con el objetivo de minimizar el número de desplazamientos que deben realizar al estudio de grabación.

2. Se ha calculado el espacio de posibles soluciones, y se ha llegado a la conclusión de que crece factorialmente.

3. Se han escogido los algoritmos genéticos como mecanismo para encontrar soluciones factibles en un tiempo razonable. Se ha experimentado con 5 y 6 días, y se ha alcanzado un mínimo coste de **27 unidades** para el caso de 5 días.

4. Para tratar de mejorar la velocidad de convergencia, se ha integrado un proceso de búsqueda local tanto para generar la población inicial como para intentar mejorar la solución final. Según los resultados, se requieren menos generaciones para alcanzar el mínimo de 27, pero no se ha conseguido mejorar dicho umbral.

5. Según los análisis previos, el coste mínimo alcanzable es **21**. Por tanto, hay una diferencia de coste de 6 unidades entre lo obtenido y lo _potencialmente_ alcanzable (28%, pero no tiene por qué existir tal solución).

6. No se ha observado mejora al aumentar el número total de días en los que grabar las escenas. Fuera de la entrega, se ha simulado el caso de 7, 8 y 9 días, sin conseguir disminuir el valor 27. Si el mejor caso se encuentra al minimizar el número de días, aumentarlo solo amplía el espacio de soluciones a explorar por el algoritmo, ralentizando su labor (siempre puede dejar días sin grabaciones, pero tiene que probar esas combinaciones).